### ISSUE TITLE
creating fixtures using dumpdata

### ISSUE THREAD

**Issue by coleifer** [bconstantin/django_polymorphic#4]
When creating fixtures using dumpdata, it does not output the base class with attributes and the subclass.  It outputs two copies of the subclass without the baseclasses attributes.

**Comment by coleifer** [comment]
also, content-type ids seem to change when running tests, so this may be pointless anyways

**Comment by bconstantin** [comment]
It turns out the dumpdata command needs a small patch. It relies on non-polymorphic behavior of the querysets, which causes this problem. I will update the repo soon.

The general stability of content type ids is something that probably needs more investigation (perhaps they only change if models are added).

**Comment by coleifer** [comment]
Aye, ctype ids are a pain with fixtures.  I believe one of my friends has solved this:
http://github.com/ericholscher/sandbox/blob/master/serializers/jsonfk.py

Also heard this was going to get fixed in 1.2 so it may not be an issue for you.

**Comment by bconstantin** [comment]
Thanks, I'll look into jsonfk.py.
For now I'll note the problem in the docs as a known potential gotcha.
